### ISSUE TITLE
Non-existant file still gets its success callback called

### ISSUE THREAD

**Issue by fresheneesz** [ded/script.js#65]
The following prints out "shouldnthappen"

```
$script('doesntExist.js', function() {
  console.log('shouldnthappen')
}, function(notFound) {
    console.log(notFound)
})
```

This makes me think script.js isn't in any way production ready.

**Comment by kzap** [comment]
+1 just read this now, pls update README to indicate callback will fire in the event of failure to load the script, been searching for hours for this answer

**Comment by amorey** [comment]
@kzap - I believe this behavior exists in `script.js` because older browsers don't support the `onerror` callback. Here's a script loader for modern browsers (IE9+) that has the same API as `script.js` and adds support for success/fail callbacks https://github.com/muicss/loadjs

**Comment by kzap** [comment]
@amorey the behaviour is fine, the documentation could be more verbose :)
